"use client";
import { useState } from "react";
import { useFormStatus } from "react-dom";
import Image from "next/image";
import { ArrowRight, Eye, EyeOff, LockKeyhole, Mail, UserRound, Phone, MapPin } from "lucide-react";
import { createCustomerAccount, loginCustomer } from "@/actions/admin";
type Availability={recovery:boolean};
function Submit({children}:{children:React.ReactNode}) {const {pending}=useFormStatus();return <button className="login-primary" disabled={pending}>{pending?"Aguarde…":children}<ArrowRight size={18}/></button>;}
function Password({confirm=false,newPassword=false}:{confirm?:boolean;newPassword?:boolean}) {const [show,setShow]=useState(false);const id=confirm?"confirmPassword":"password";return <label className="login-field" htmlFor={id}><span>{confirm?"Confirmar palavra-passe":"Palavra-passe"}</span><div><LockKeyhole size={20}/><input aria-label={confirm?"Confirmar palavra-passe":"Palavra-passe"} id={id} name={id} type={show?"text":"password"} autoComplete={confirm||newPassword?"new-password":"current-password"} minLength={6} maxLength={72} required placeholder={confirm?"Repita a palavra-passe":"A sua palavra-passe"}/><button type="button" aria-label={`${show?"Ocultar":"Mostrar"} ${confirm?"confirmação da palavra-passe":"palavra-passe"}`} aria-pressed={show} onClick={()=>setShow(!show)}>{show?<EyeOff size={20}/>:<Eye size={20}/>}</button></div></label>;}
export function CustomerLogin({availability,imageUrl,imageAlt,initialMode,error,resetToken,whatsapp}:{availability:Availability;imageUrl:string;imageAlt:string;initialMode:"login"|"register";error:string;resetToken?:string;whatsapp:string}) {
  const [mode,setMode]=useState<"login"|"register"|"recovery"|"reset">(resetToken?"reset":initialMode);const [message,setMessage]=useState(error);const [busy,setBusy]=useState(false);const [imageFailed,setImageFailed]=useState(false);
  const register=mode==="register";const recovery=mode==="recovery"||mode==="reset";
  function switchMode(next:typeof mode){setMode(next);setMessage("");}
  async function recover(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const form=new FormData(event.currentTarget);try{const body=mode==="reset"?{token:resetToken,password:form.get("password"),confirmPassword:form.get("confirmPassword")}:{email:form.get("email")};const response=await fetch("/api/auth/recovery",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();setMessage(result.error||result.message);if(response.ok&&mode==="reset")setMode("login");}catch{setMessage("Não foi possível concluir. Tente novamente.");}finally{setBusy(false);}}
  const email=<label className="login-field" htmlFor="email"><span>Email</span><div><Mail size={20}/><input id="email" name="email" type="email" autoComplete="email" required maxLength={254} placeholder="O seu email"/></div></label>;
  return <div className="premium-login"><section className="login-stage"><div className="login-hero"><div className="login-photo">{imageUrl&&!imageFailed&&<Image src={imageUrl} alt={imageAlt} fill priority sizes="(max-width: 767px) 180px, 500px" onError={()=>setImageFailed(true)}/>}</div><div className="login-heading"><p>{register?"Criar conta":recovery?"A sua conta":"Bem-vindo(a)"}</p><h1>{register?"Junte-se à\n9 Ilhas":mode==="recovery"?"Recuperar\npalavra-passe":mode==="reset"?"Nova\npalavra-passe":"Entre na\nsua conta"}</h1><p className="login-description">{register?"Guarde os seus favoritos, dados e promoções.":recovery?"Volte a aceder à sua conta em segurança.":"Aceda aos seus favoritos, dados e promoções."}</p></div></div><div className="login-panel" key={mode}>
    {message&&<p className="login-message" role="status">{message}</p>}
    {!recovery?<><form action={register?createCustomerAccount:loginCustomer} className="login-form">{register&&<><div className="login-names">{([['firstName','Nome'],['lastName','Apelido']] as const).map(([id,label])=><label key={id} className="login-field" htmlFor={id}><span>{label}</span><div><UserRound size={20}/><input id={id} name={id} autoComplete={id==="firstName"?"given-name":"family-name"} minLength={2} maxLength={100} required placeholder={`O seu ${label.toLowerCase()}`}/></div></label>)}</div></>}{email}{register&&<><label className="login-field" htmlFor="phone"><span>Telefone</span><div><Phone size={20}/><input id="phone" name="phone" type="tel" autoComplete="tel" minLength={6} maxLength={30} required placeholder="Número de telefone"/></div></label><label className="login-field" htmlFor="address"><span>Morada</span><div><MapPin size={20}/><input id="address" name="address" autoComplete="street-address" minLength={6} maxLength={500} required placeholder="A sua morada"/></div></label></>}<Password newPassword={register}/>{register&&<Password confirm/>}{!register&&<button type="button" className="login-recover" onClick={()=>switchMode("recovery")}>Recuperar palavra-passe</button>}<Submit>{register?"Criar conta":"Entrar"}</Submit></form><button type="button" className="login-switch" onClick={()=>switchMode(register?"login":"register")}><UserRound size={25}/><span>{register?"Já tem conta?":"Ainda não tem conta?"}<strong>{register?"Entrar agora":"Criar conta"} <ArrowRight size={17}/></strong></span></button></>:<><form onSubmit={recover} className="login-form">{mode==="reset"?<><Password newPassword/><Password confirm/></>:email}{availability.recovery?<button className="login-primary" disabled={busy}>{busy?"Aguarde…":mode==="reset"?"Guardar palavra-passe":"Enviar instruções"}<ArrowRight size={18}/></button>:<p className="login-message">A recuperação por email ainda não está disponível. <a href={whatsapp}>Contacte a loja</a>.</p>}</form><button type="button" className="login-switch" onClick={()=>switchMode("login")}><span>Já tem acesso?<strong>Entrar agora <ArrowRight size={17}/></strong></span></button></>}
  </div></section></div>;
}
