"use client";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { InventoryDialog } from "./inventory-dialog";
import { homepageSectionLabels, homepageEditorSchema, type HomepageEditorConfig, type HomepageSection } from "@/lib/homepage-config";
type Choice={id:string;name:string;imageUrl:string};
type Value=string|number|boolean|Value[]|{[key:string]:Value};
const labels:Record<string,string>={active:"Mostrar",order:"Ordem",title:"Título",text:"Texto",imageUrl:"Imagem",buttonLabel:"Texto do botão",href:"Destino da ligação",eyebrow:"Texto acima do título",benefitsActive:"Mostrar benefícios",visibleCount:"Produtos visíveis no desktop"};
const field="mt-1 min-h-10 w-full min-w-0 rounded-xl border bg-white px-3 py-2 text-sm";
export function HomepageEditor({initial,version:initialVersion,images}:{initial:HomepageEditorConfig;version:string;images:Choice[]}) {
 const [config,setConfig]=useState(initial);const [version,setVersion]=useState(initialVersion);const [busy,setBusy]=useState(false);const [uploading,setUploading]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");const [picker,setPicker]=useState<string[]|null>(null);const [query,setQuery]=useState("");const [uploaded,setUploaded]=useState<Choice[]>([]);
 function change(path:string[],value:Value){setMessage("");setConfig(current=>{const next=structuredClone(current);let node=next as unknown as Record<string,Value>;for(const key of path.slice(0,-1))node=node[key] as Record<string,Value>;node[path.at(-1)!]=value;return next;});}
 async function upload(path:string[],file:File){setUploading(true);setError("");try{const form=new FormData();form.set("file",file);const response=await fetch("/api/admin/homepage/image",{method:"POST",body:form});const data=await response.json();if(!response.ok)throw new Error(data.error);change(path,data.url);setUploaded(v=>[{id:data.url,name:file.name,imageUrl:data.url},...v]);}catch(e){setError(e instanceof Error?e.message:"Erro ao carregar imagem.");}finally{setUploading(false);}}
 async function save(){setBusy(true);setMessage("");setError("");try{const valid=homepageEditorSchema.safeParse(config);if(!valid.success)throw new Error("Verifique os destinos, a ordem e o número de produtos (1 a 6).");const response=await fetch("/api/admin/homepage",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"editor",editor:valid.data,version})});const data=await response.json();if(!response.ok)throw new Error(data.error);setVersion(data.version);setMessage("Página inicial guardada. As alterações já estão na loja.");}catch(e){setError(e instanceof Error?e.message:"Não foi possível guardar.");}finally{setBusy(false);}}
 // Native disclosure state can change before hydration or be restored by the browser.
 function render(value:Value,path:string[]):React.ReactNode {
  const key=path.at(-1)!;const label=labels[key]??key;if(key==="key")return null;
  if(typeof value==="boolean")return <label key={path.join(".")} className="flex min-h-10 items-center gap-2 text-sm"><input type="checkbox" checked={value} onChange={e=>change(path,e.target.checked)}/>{label}</label>;
  if(typeof value==="number")return <label key={path.join(".")} className="block text-sm">{label}<input type="number" min={key==="visibleCount"?1:0} max={key==="visibleCount"?6:1000} value={value} className={field} onChange={e=>change(path,Number(e.target.value))}/></label>;
  if(typeof value==="string") {
   if(key==="imageUrl")return <div key={path.join(".")} className="min-w-0 space-y-2"><p className="text-sm">Imagem</p>{value?<Image src={value} alt="Pré-visualização" width={160} height={110} unoptimized className="h-24 max-w-full rounded-xl border bg-white object-contain"/>:null}<input aria-label="Endereço da imagem" className={field} value={value} onChange={e=>change(path,e.target.value)} placeholder="Endereço da imagem (opcional)"/><div className="flex flex-wrap gap-2"><label className="cursor-pointer rounded-xl border px-3 py-2 text-xs">Carregar / substituir<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" className="sr-only" disabled={uploading} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(path,file);e.target.value="";}}/></label><button type="button" className="rounded-xl border px-3 py-2 text-xs" onClick={()=>{setQuery("");setPicker(path);}}>Escolher imagem</button>{value?<button type="button" className="rounded-xl border px-3 py-2 text-xs" onClick={()=>change(path,"")}>Remover imagem</button>:null}</div></div>;
   return <label key={path.join(".")} className="block min-w-0 text-sm">{label}{key==="text"?<textarea className={field} rows={3} value={value} onChange={e=>change(path,e.target.value)}/>:<input className={field} value={value} onChange={e=>change(path,e.target.value)}/>}</label>;
  }
  if(Array.isArray(value))return <div key={path.join(".")} className="space-y-3 md:col-span-2">{value.map((item,index)=><details suppressHydrationWarning key={index} className="rounded-xl border p-3"><summary className="cursor-pointer text-sm font-semibold">{typeof item==="object"&&!Array.isArray(item)?String(item.title||`Elemento ${index+1}`):`Elemento ${index+1}`}</summary><div className="mt-3 grid min-w-0 gap-3 md:grid-cols-2">{render(item,[...path,String(index)])}</div><div className="mt-3 flex gap-2">{[-1,1].map(direction=>index+direction>=0&&index+direction<value.length?<button type="button" key={direction} className="rounded-lg border px-2 py-1 text-xs" onClick={()=>{const next=[...value];[next[index+direction],next[index]]=[next[index],next[index+direction]];change(path,next.map((v,i)=>typeof v==="object"&&!Array.isArray(v)&&"order" in v?{...v,order:i}:v));}}>{direction<0?"Subir":"Descer"}</button>:null)}</div></details>)}{path[0]==="collections"?<button type="button" className="rounded-xl border px-3 py-2 text-sm" onClick={()=>change(path,[...value,{key:crypto.randomUUID(),title:"Nova categoria",imageUrl:"",href:"/catalogo",active:true,order:value.length}])}>Adicionar categoria</button>:null}</div>;
  return <>{Object.entries(value).map(([child,v])=>render(v,[...path,child]))}</>;
 }
 return <div className="min-w-0 space-y-3"><div className="flex flex-wrap items-center gap-3"><button type="button" onClick={()=>void save()} disabled={busy||uploading} className="min-h-11 rounded-xl bg-[color:var(--atlantic)] px-5 py-2 text-sm text-white disabled:opacity-50">{busy?"A guardar…":"Guardar página inicial"}</button><Link href="/" target="_blank" className="text-sm underline">Pré-visualizar loja</Link></div><p className="text-xs text-slate-500">Abra uma secção para editar. Campos vazios são ocultados. A ordem menor aparece primeiro. Guarde para publicar.</p>{message?<p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{message}</p>:null}{error?<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}{uploading?<p role="status" className="text-sm">A carregar imagem…</p>:null}
 {(Object.keys(homepageSectionLabels) as HomepageSection[]).map(section=><details suppressHydrationWarning key={section} className="rounded-2xl border border-[color:var(--line)] bg-white p-4"><summary className="cursor-pointer font-semibold">{homepageSectionLabels[section]} <span className="ml-2 text-xs font-normal text-slate-500">{config[section].active?"Visível":"Oculta"}</span></summary>{section==="featured"?<p className="my-3 text-sm text-slate-500">A seleção é a mesma de <Link href="/admin/produtos" className="underline">Produtos / Preferidos da homepage</Link>. Não cria outra lista.</p>:null}{section==="daily"?<p className="my-3 text-sm text-slate-500">Escolha o perfume no <Link href="/admin" className="underline">Dashboard</Link>. Aqui controla apenas a apresentação. Ocultar esta secção mantém a promoção ativa.</p>:null}<div className="mt-3 grid min-w-0 gap-4 md:grid-cols-2">{render(config[section] as unknown as Value,[section])}</div></details>)}
 {picker?<InventoryDialog title="Escolher imagem existente" onClose={()=>setPicker(null)}><input type="search" aria-label="Pesquisar imagem" className={field} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar produto…"/><div className="mt-3 grid max-h-[50dvh] grid-cols-2 gap-3 overflow-y-auto">{[...uploaded,...images].filter(i=>i.name.toLowerCase().includes(query.toLowerCase())).map(i=><button type="button" key={i.id} className="min-w-0 rounded-xl border p-2 text-left" onClick={()=>{change(picker,i.imageUrl);setPicker(null);}}><Image src={i.imageUrl} alt="" width={96} height={96} unoptimized className="h-20 w-full object-contain"/><span className="block break-words text-xs">{i.name}</span></button>)}</div></InventoryDialog>:null}
 </div>;
}
