ALTER TABLE "StoreSettings"
ADD COLUMN "heroPrimaryButtonLabel" TEXT NOT NULL DEFAULT 'Ver Catálogo',
ADD COLUMN "heroSecondaryButtonLabel" TEXT NOT NULL DEFAULT 'Sobre Nós',
ADD COLUMN "heroBenefitOne" TEXT NOT NULL DEFAULT 'Perfumes 100% Originais',
ADD COLUMN "heroBenefitTwo" TEXT NOT NULL DEFAULT 'Entrega rápida na Ilha Terceira',
ADD COLUMN "heroBenefitThree" TEXT NOT NULL DEFAULT 'Atendimento personalizado por WhatsApp',
ADD COLUMN "heroBenefitFour" TEXT NOT NULL DEFAULT 'Amostras disponíveis em 5ml',
ADD COLUMN "homeFeaturedEyebrow" TEXT NOT NULL DEFAULT 'Mais vendidos',
ADD COLUMN "homeFeaturedTitle" TEXT NOT NULL DEFAULT 'Os Preferidos dos Nossos Clientes',
ADD COLUMN "homeFeaturedDescription" TEXT NOT NULL DEFAULT 'As fragrâncias mais procuradas e recomendadas pelos nossos clientes.',
ADD COLUMN "homeFeaturedButtonLabel" TEXT NOT NULL DEFAULT 'Ver todos',
ADD COLUMN "homeDecantsEyebrow" TEXT NOT NULL DEFAULT 'Serviço complementar',
ADD COLUMN "homeDecantsTitle" TEXT NOT NULL DEFAULT 'Experimente antes de comprar',
ADD COLUMN "homeDecantsDescription" TEXT NOT NULL DEFAULT 'Decants de 5ml e 10ml disponíveis em perfumes selecionados.',
ADD COLUMN "homeDecantsButtonLabel" TEXT NOT NULL DEFAULT 'Ver Decants',
ADD COLUMN "homeWhyChooseEyebrow" TEXT NOT NULL DEFAULT 'Confiança',
ADD COLUMN "homeWhyChooseTitle" TEXT NOT NULL DEFAULT 'Porque Comprar na Perfumaria 9 Ilhas?',
ADD COLUMN "whyChooseItemOneTitle" TEXT NOT NULL DEFAULT 'Entrega rápida na Ilha Terceira',
ADD COLUMN "whyChooseItemOneText" TEXT NOT NULL DEFAULT 'Receba com rapidez e acompanhamento próximo.',
ADD COLUMN "whyChooseItemTwoTitle" TEXT NOT NULL DEFAULT 'Envio para Açores, Madeira e Portugal Continental',
ADD COLUMN "whyChooseItemTwoText" TEXT NOT NULL DEFAULT 'Preparamos cada encomenda com atenção e segurança.',
ADD COLUMN "whyChooseItemThreeTitle" TEXT NOT NULL DEFAULT 'Perfumes 100% Originais',
ADD COLUMN "whyChooseItemThreeText" TEXT NOT NULL DEFAULT 'Selecionamos referências autênticas e confiáveis.',
ADD COLUMN "whyChooseItemFourTitle" TEXT NOT NULL DEFAULT 'Atendimento via WhatsApp',
ADD COLUMN "whyChooseItemFourText" TEXT NOT NULL DEFAULT 'Respondemos de forma próxima e personalizada.',
ADD COLUMN "whyChooseItemFiveTitle" TEXT NOT NULL DEFAULT 'Pagamento Seguro',
ADD COLUMN "whyChooseItemFiveText" TEXT NOT NULL DEFAULT 'Confirmação clara antes de finalizar a encomenda.',
ADD COLUMN "homeTestimonialsEyebrow" TEXT NOT NULL DEFAULT 'Testemunhos',
ADD COLUMN "homeTestimonialsTitle" TEXT NOT NULL DEFAULT 'O que dizem os nossos clientes';
